on:
  workflow_dispatch:
  schedule:
    # Audit repos twice a day.
    - cron:  '0 0,12 * * *'

name: GitHub Audit

jobs:
  ghaudit:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # To federate with Octo STS

    steps:
    - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
      id: octo-sts
      with:
        scope: ${{ github.repository_owner }}
        identity: my-test-repo-ghaudit

    - uses: actions/checkout@v4
      with:
        token:  ${{ steps.octo-sts.outputs.token }}
        repository: ${{ github.repository_owner }}/source

    # - uses: actions/checkout@v4
    #   with:
    #     token:  ${{ steps.octo-sts.outputs.token }}
    #     repository: ${{ github.repository_owner }}/source-02

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.TOKEN_APP_ID }}
        private-key: ${{ secrets.TOKEN_APP_CERT }}
    
    - uses: actions/checkout@v4
      name: Checkout via App token
      with:
        token:  ${{ steps.octo-sts.outputs.token }}
        repository: ${{ github.repository_owner }}/source-02
